// Vacancy
export const ACTION_GET_VACANCIES_STARTED = "GET_VACANCIES_STARTED";
export const ACTION_GET_VACANCIES_SUCCESS = "GET_VACANCIES_SUCCESS";
export const ACTION_GET_VACANCIES_FAILED = "GET_VACANCIES_FAILED";

export const ACTION_CREATE_VACANCY_STARTED = "CREATE_VACANCY_STARTED";
export const ACTION_CREATE_VACANCY_SUCCESS = "CREATE_VACANCY_SUCCESS";

// User
export const ACTION_GET_USER_STARTED = "GET_USER_STARTED";
export const ACTION_GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const ACTION_GET_USER_FAILED = "GET_USER_FAILED";

export const ACTION_CREATE_USER_STARTED = "CREATE_USER_STARTED";
export const ACTION_CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";

export const ACTION_LOGIN_STARTED = "LOGIN_STARTED";
export const ACTION_LOGIN_SUCCESS = "LOGIN_SUCCESS";